### ISSUE TITLE
有跳转各个题目的书签就好了

### ISSUE THREAD

**Issue by ccsugar** [Fantasia1999/kaoyanzhenti#1]
如题

**Comment by Fantasia1999** [comment]
其实这个文档的初衷是打印用的，就没考虑电子版的使用场景。感觉题目跳转意义不大啊，基本上题都和Text挨着的。每道题都加上去的话，目录太长了，在阅读器里面，不好翻。倒是可以考虑一下每5道题或者1-20、21-25、26-30、31-35、36-40、41-45、46-50、51、52这样加一下

**Comment by ccsugar** [comment]
不是题号跳转，是text1、text2、新题型、翻译这样的书签

**Comment by Fantasia1999** [comment]
可以，我稍后加一下。

**Comment by ccsugar** [comment]
谢谢你😊
