### ISSUE TITLE
是否可以提供word版本？

### ISSUE THREAD

**Issue by Chengyue-Liu** [Fantasia1999/kaoyanzhenti#4]
您好，是否可以提供word版本的真题，想做一些提取单词之类的程序。

**Comment by Fantasia1999** [comment]
可以先看这位大佬整理的LaTex版本，不过只有英语一。
https://gitee.com/ylxdxx/EN201-kaoyan

> LaTex的排版是非常精美的，但是由于某些文章的篇幅较长，出现了一些换页的问题，导致并不完全契合考场版（这也是为什么没有按照这个版本来更新文档）。但是对于提取单词来说，已经够用了。
